theme: slate
title: [AI Gahaku & Racial Bias in Pix2Pix GAN Art]
description: [This website explores the Pix2Pix GAN AI Gahaku and determine whether it produces unequal results depending on user's ethnicity.]
